### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by arthuro555**
- Remove unused web vitals
- Add pre-commit hook to run prettier and eslint on staged files via husky & lint-staged
- Capitalize file names
- Move firebase to utils folder
- Remove unused files
- Use MUI CssBaseline

Smaller PR and separated all changes in small commits to make it easier to isolate any issues with the changes.

### CODE REVIEW

**Comment by AdvaitDhingra** [comment]
Thanks for the PR. I'm gonna test these changes first before I merge.

**Comment by AdvaitDhingra** [comment]
The css is a bit messed up. can you fix this? The posts are all crooked.

**Comment by arthuro555** [comment]
🤔 I don't see what you mean, there is no difference in the posts for me. The only styling difference is a slightly changed font in the toolbar as far as I see.

**Comment by AdvaitDhingra** [comment]
> 🤔 I don't see what you mean, there is no difference in the posts for me. The only styling difference is a slightly changed font in the toolbar as far as I see.

**Comment by arthuro555** [comment]
I have something else on both netlify and locally:
image  
image

**Comment by AdvaitDhingra** [comment]
> I have something else on both netlify and locally:
> image
> image

Thats strange. Maybe I'll merge this and see what comes out. Don't delete your branch, as if I get the same result I will reset the commit. Lets just see.

**Comment by AdvaitDhingra** [comment]
Okay it seems to have worked. Must be something wring with my setup. Good job :D

**Pull request merged**
